<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ShoppInMap - Encontre todos os mapas dos shoppings em um unico lugar">
    <meta name="author" content="Avalon Soluções">
    <link rel="shortcut icon" href="/web-files/ico/favicon.ico">
    
    <title><?php echo PROJETO_NOME . "". ( isset($subtitulo) ? $subtitulo:"");?></title>
       
    <link href="/web-files/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/web-files/bootstrap/css/starter-template.css" rel="stylesheet">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
